In [1]:
import glob
import pandas as pd
import numpy as np

In [91]:
def is_empty(e):
    if e is None:
        return True
    if isinstance(e, str) and not e:
        return True
    if isinstance(e, float) and np.isnan(e):
        return True
    if hasattr(e, '__len__') and len(e) == 0:
        return True
    return False

def is_string(e):
    if isinstance(e, str) and e:
        return True
    return False

def is_number(e):
    if isinstance(e, float) and not np.isnan(e):
        return True
    if isinstance(e, str) and e:
        return (e
                .replace(" ", "")
                .replace("-", "")
                .replace("%", "")
                .replace(",", "")
                .isdigit()
               )
    return False

def identification_mask(pdf):
    def substitute(e):
        if is_empty(e):
            return None
        if is_number(e):
            return "n"
        if is_string(e):
            return "s"
    return pdf.applymap(substitute)

In [92]:
ic = identification_mask(c)

In [93]:
ic

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,None,None,None,None,None,None,None,None,None,None,...,s,None,None,None,None,None,None,None,None,s
1,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,s
2,None,None,n,None,n,None,n,None,n,None,...,n,n,None,n,None,n,None,n,s,s
3,s,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,n,n
4,s,None,n,None,n,None,n,None,n,None,...,n,n,None,n,None,n,None,n,None,n
5,s,None,n,None,n,None,n,None,n,None,...,n,n,None,n,None,n,None,None,None,n
6,s,None,n,None,n,None,n,None,n,None,...,n,n,None,n,None,None,None,None,None,n
7,s,None,n,None,n,None,n,None,n,None,...,n,n,None,None,None,None,None,None,None,n
8,s,None,n,None,n,None,n,None,n,None,...,n,None,None,None,None,None,None,None,None,n
9,s,None,n,None,n,None,n,None,n,None,...,None,None,None,None,None,None,None,None,None,n
10,s,None,n,None,n,None,n,None,n,None,...,None,None,None,None,None,None,None,None,None,n
11,s,None,n,None,n,None,n,None,None,None,...,None,None,None,None,None,None,None,None,None,n
12,s,None,n,None,n,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,n
13,None,s,n,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,n
14,s,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,n

In [94]:
def identify_number_area(c):
    ic = identification_mask(c)
    r1, r2 = iter(range(c.shape[0]-1, -1, -1)), iter(range(c.shape[1]-1, -1, -1))

    i, j = 1, 1
    ie, je = -1, -1

    while True:
        if ie == -1:
            i = next(iter(r1))
        if je == -1:
            j = next(iter(r2))
        
        if (ic.iloc[i, j+1:] == 's').any():
            ie = i + 1
        if i == 0 and ie == -1:
            ie = 0
        
        if (ic.iloc[i+1:, j] == 's').any():
            je = j + 1
        if j == 0 and je == -1:
            je = 0
        
        if ie != -1 and ie != -1:
            return ie, je

In [201]:
def squeeze_headers(c, number_area):
    
    def apply_transform(s):
        return s.apply(str).apply(lambda x: "" if x == "NaN" else x)
    
    sc = c.applymap(lambda x: "NaN" if isinstance(x, float) and np.isnan(x) else x)
    ie, je = number_area
    
    l1 = None
    for i in range(0, ie):
        if l1 is None:
            l1 = apply_transform(sc.iloc[0, :])
        else:
            l1 = l1.str.cat(apply_transform(sc.iloc[i]), sep=' ')
    if l1 is not None:
        sc = pd.concat([l1.to_frame().T, sc.drop(axis=0, index=range(0, ie))])
    
    l2 = None
    for i in range(0, je):
        if l2 is None:
            l2 = apply_transform(sc.iloc[:, 0])
        else:
            l2 = l2.str.cat(apply_transform(sc.iloc[:, i]), sep=' ')
    if l2 is not None:
        sc = pd.concat([l2.to_frame(), sc.drop(axis=1, columns=range(0, je))], axis=1)
    
    if l1 is not None:
        sc.iloc[0, :] = [f"*{i}" if x.strip() == "" else x for i, x in enumerate(sc.iloc[0, :])]
        sc.columns = sc.iloc[0, :]
        sc = sc.drop(axis=0, index=[0])
        
    sc = sc.set_index(sc.columns[0])
    
    return sc

def squeeze_columns(sc):
    columns_to_drop = []
    for c1, c2 in zip(sc.columns[1:], sc.columns[2:]):
        all_is_nan = (sc[c1] == "NaN").all()
        if not isinstance(all_is_nan, pd.Series) and all_is_nan and c2[0] == "*":
            sc[c1] = sc[c2]
            columns_to_drop.append(c2)
            
    return sc.drop(columns=columns_to_drop)

In [205]:
total_numbers = 0
for i, f in enumerate(glob.glob("../data/res/*/*.csv", recursive=True)):
    print("parsing", i, f)
    c = pd.read_csv(f, sep=',', thousands=' ', header=None, dtype=object, encoding='UTF-8')
    display(c)
    ic = identification_mask(c)
#     display(ic)
    na = identify_number_area(c)
    print(na)
    sc = squeeze_headers(c, na)
#     display(sc)
    display(squeeze_columns(sc))
    total_numbers += (ic.iloc[na[0]:, na[1]:] == "n").count().sum()
    
print("total_numbers", total_numbers)

parsing 0 ../data/res\generali\tabula-Generali_2019_EN_short-0.csv

                                                    0                  1
0                                                 NaN  Solvency II value
1                                              Assets                NaN
2                                   Intangible assets                  0
3                                 Deferred tax assets                  0
4                             Pension benefit surplus                  0
5        Property, plant & equipment held for own use            877 909
6   Investments (other than assets held for index-...         68 036 488
7                   Property (other than for own use)            316 964
8   Holdings in related undertakings, including pa...         17 794 170
9                                            Equities          2 086 266
10                                  Equities - listed          1 375 648
11                                Equities - unlisted            710 618
12                                              Bonds         42 591 825
13                                   Government Bonds         26 209 652
14                                    Corporate Bonds         16 108 014
15                                   Structured notes             30 487
16                          Collateralised securities            243 672
17                Collective Investments Undertakings          4 517 358
18                                        Derivatives            529 905
19               Deposits other than cash equivalents            200 000
20                                  Other investments                  0
21  Assets held for index-linked and unit-linked c...         16 651 820
22                                Loans and mortgages          8 208 914
23                                  Loans on policies                190
24                 Loans and mortgages to individuals                  0
25                          Other loans and mortgages          8 208 724
26                     Reinsurance recoverables from:          7 121 154
27            Non-life and health similar to non-life          6 539 109
28                          Non-life excluding health          5 919 988
29                         Health similar to non-life            619 121
30  Life and health similar to life, excluding hea...            595 509
31                             Health similar to life                  0
32  Life excluding health and index-linked and uni...            595 509
33                  Life index-linked and unit-linked            -13 464
34                                Deposits to cedants                555
35           Insurance and intermediaries receivables          1 357 497
36                            Reinsurance receivables            451 231
37                 Receivables (trade, not insurance)          1 306 986
38                         Own shares (held directly)                  0
39  Amounts due in respect of own fund items or in...                  0
40                          Cash and cash equivalents          1 452 581
41              Any other assets, not elsewhere shown          4 599 350
42                                       Total assets        110 064 484

(1, 1)

0                                                  Solvency II value
*0
Assets                                                           NaN
Intangible assets                                                  0
Deferred tax assets                                                0
Pension benefit surplus                                            0
Property, plant & equipment held for own use                 877 909
Investments (other than assets held for index-l...        68 036 488
Property (other than for own use)                            316 964
Holdings in related undertakings, including par...        17 794 170
Equities                                                   2 086 266
Equities - listed                                          1 375 648
Equities - unlisted                                          710 618
Bonds                                                     42 591 825
Government Bonds                                          26 209 652
Corporate Bonds                                           16 108 014
Structured notes                                              30 487
Collateralised securities                                    243 672
Collective Investments Undertakings                        4 517 358
Derivatives                                                  529 905
Deposits other than cash equivalents                         200 000
Other investments                                                  0
Assets held for index-linked and unit-linked co...        16 651 820
Loans and mortgages                                        8 208 914
Loans on policies                                                190
Loans and mortgages to individuals                                 0
Other loans and mortgages                                  8 208 724
Reinsurance recoverables from:                             7 121 154
Non-life and health similar to non-life                    6 539 109
Non-life excluding health                                  5 919 988
Health similar to non-life                                   619 121
Life and health similar to life, excluding heal...           595 509
Health similar to life                                             0
Life excluding health and index-linked and unit...           595 509
Life index-linked and unit-linked                            -13 464
Deposits to cedants                                              555
Insurance and intermediaries receivables                   1 357 497
Reinsurance receivables                                      451 231
Receivables (trade, not insurance)                         1 306 986
Own shares (held directly)                                         0
Amounts due in respect of own fund items or ini...                 0
Cash and cash equivalents                                  1 452 581
Any other assets, not elsewhere shown                      4 599 350
Total assets                                             110 064 484

parsing 1 ../data/res\generali\tabula-Generali_2019_EN_short-1.csv

                                                    0           1
0                     Technical provisions - non-life  17 087 523
1   Technical provisions - non-life (excluding hea...  15 157 230
2                            TP calculated as a whole           0
3                                       Best estimate  14 449 245
4                                         Risk margin     707 985
5   Technical provisions - health (similar to non-...   1 930 293
6                            TP calculated as a whole           0
7                                       Best estimate   1 904 108
8                                         Risk margin      26 185
9   Technical provisions - life (excluding index-l...  26 015 167
10    Technical provisions - health (similar to life)           0
11                           TP calculated as a whole           0
12                                      Best estimate           0
13                                        Risk margin           0
14  Technical provisions – life (excluding health ...  26 015 167
15                           TP calculated as a whole           0
16                                      Best estimate  24 975 327
17                                        Risk margin   1 039 840
18  Technical provisions – index-linked and unit-l...  15 037 345
19                           TP calculated as a whole           0
20                                      Best estimate  14 671 043
21                                        Risk margin     366 302
22                         Other technical provisions           0
23                             Contingent liabilities           0
24         Provisions other than technical provisions      56 542
25                        Pension benefit obligations           0
26                           Deposits from reinsurers   1 400 000
27                           Deferred tax liabilities   1 352 555
28                                        Derivatives     438 163
29                  Debts owed to credit institutions   4 550 774
30  Financial liabilities other than debts owed to...   1 079 986
31                Insurance & intermediaries payables           0
32                               Reinsurance payables           0
33                    Payables (trade, not insurance)   2 566 524
34                           Subordinated liabilities           0
35                Subordinated liabilities not in BOF           0
36                    Subordinated liabilities in BOF           0
37         Any other liabilities, not elsewhere shown  11 219 160
38                                  Total liabilities  80 803 741
39                  Excess of assets over liabilities  29 260 743

(0, 1)

                                                             1
0
Technical provisions - non-life                     17 087 523
Technical provisions - non-life (excluding health)  15 157 230
TP calculated as a whole                                     0
Best estimate                                       14 449 245
Risk margin                                            707 985
Technical provisions - health (similar to non-l...   1 930 293
TP calculated as a whole                                     0
Best estimate                                        1 904 108
Risk margin                                             26 185
Technical provisions - life (excluding index-li...  26 015 167
Technical provisions - health (similar to life)              0
TP calculated as a whole                                     0
Best estimate                                                0
Risk margin                                                  0
Technical provisions – life (excluding health a...  26 015 167
TP calculated as a whole                                     0
Best estimate                                       24 975 327
Risk margin                                          1 039 840
Technical provisions – index-linked and unit-li...  15 037 345
TP calculated as a whole                                     0
Best estimate                                       14 671 043
Risk margin                                            366 302
Other technical provisions                                   0
Contingent liabilities                                       0
Provisions other than technical provisions              56 542
Pension benefit obligations                                  0
Deposits from reinsurers                             1 400 000
Deferred tax liabilities                             1 352 555
Derivatives                                            438 163
Debts owed to credit institutions                    4 550 774
Financial liabilities other than debts owed to ...   1 079 986
Insurance & intermediaries payables                          0
Reinsurance payables                                         0
Payables (trade, not insurance)                      2 566 524
Subordinated liabilities                                     0
Subordinated liabilities not in BOF                          0
Subordinated liabilities in BOF                              0
Any other liabilities, not elsewhere shown          11 219 160
Total liabilities                                   80 803 741
Excess of assets over liabilities                   29 260 743

parsing 2 ../data/res\generali\tabula-Generali_2019_EN_short-10.csv

,0,1,2,3,4,5
0,NaN,Amount with Long,NaN,NaN,NaN,NaN
1,NaN,Term Guarantee,Impact of transitional,Impact of transitional,Impact of volatility,Impact of matching
2,NaN,measures and,on technical provisions,on interest rate,adjustment set to zero,adjustment set to zero
3,NaN,transitionals,NaN,NaN,NaN,NaN
4,Technical provisions,58 140 035,0,0,286 120,0
5,Basic own funds,26 043 743,0,0,-184 939,0
6,Eligible own funds to meet Solvency Capital Re...,26 043 743,0,0,-184 939,0
7,Solvency Capital Requirement,12 883 886,0,0,533 439,0
8,Eligible own funds to meet Minimum Capital Req...,26 043 743,0,0,-184 939,0
9,Minimum Capital Requirement,3 220 972,0,0,133 360,0

(4, 1)

,Amount with Long Term Guarantee measures and transitionals,Impact of transitional on technical provisions,Impact of transitional on interest rate,Impact of volatility adjustment set to zero,Impact of matching adjustment set to zero
*0,,,,,
Technical provisions,58 140 035,0,0,286 120,0
Basic own funds,26 043 743,0,0,-184 939,0
Eligible own funds to meet Solvency Capital Requirement,26 043 743,0,0,-184 939,0
Solvency Capital Requirement,12 883 886,0,0,533 439,0
Eligible own funds to meet Minimum Capital Requirement,26 043 743,0,0,-184 939,0
Minimum Capital Requirement,3 220 972,0,0,133 360,0

parsing 3 ../data/res\generali\tabula-Generali_2019_EN_short-11.csv

,0,1,2,3,4,5,6,7,8
0,NaN,Total,Tier 1 - unrestricted,Tier 1 - restricted,NaN,Tier 2,NaN,Tier 3,NaN
1,Basic own funds before deduction for participa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Regulation (EU) 2015/35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ordinary share capital (gross of own shares),4 000 000,4 000 000,NaN,NaN,NaN,0,NaN,NaN
4,Share premium account related to ordinary shar...,0,0,NaN,NaN,NaN,0,NaN,NaN
5,"Initial funds, members' contributions or the e...",0,0,NaN,NaN,NaN,0,NaN,NaN
6,Subordinated mutual member accounts,0,NaN,NaN,0,NaN,0,NaN,0
7,Surplus funds,0,0,NaN,NaN,NaN,NaN,NaN,NaN
8,Preference shares,0,NaN,NaN,0,NaN,0,NaN,0
9,Share premium account related to preference sh...,0,NaN,NaN,0,NaN,0,NaN,0
10,Reconciliation reserve,22 043 743,22 043 743,NaN,NaN,NaN,NaN,NaN,NaN
11,Subordinated liabilities,0,NaN,NaN,0,NaN,0,NaN,0
12,An amount equal to the value of net deferred t...,0,NaN,NaN,NaN,NaN,NaN,NaN,0
13,Other own fund items approved by the superviso...,0,0,NaN,0,NaN,0,NaN,0
14,Own funds from the financial statements that s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,criteria to be classified as Solvency II own f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Own funds from the financial statements that s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,to be classified as Solvency II own funds,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Deductions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Deductions for participations in financial and...,0,0,NaN,0,NaN,0,NaN,0
20,Total basic own funds after deductions,26 043 743,26 043 743,NaN,0,NaN,0,NaN,0
21,Ancillary own funds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Unpaid and uncalled ordinary share capital cal...,0,NaN,NaN,NaN,NaN,0,NaN,NaN
23,"Unpaid and uncalled initial funds, members' co...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,"undertakings, callable on demand",0,NaN,NaN,NaN,NaN,0,NaN,NaN
25,Unpaid and uncalled preference shares callable...,0,NaN,NaN,NaN,NaN,0,NaN,0
26,A legally binding commitment to subscribe and ...,0,NaN,NaN,NaN,NaN,0,NaN,0
27,Letters of credit and guarantees under Article...,0,NaN,NaN,NaN,NaN,0,NaN,NaN
28,Letters of credit and guarantees other than un...,0,NaN,NaN,NaN,NaN,0,NaN,0
29,Supplementary members calls under first subpar...,0,NaN,NaN,NaN,NaN,0,NaN,NaN
30,Supplementary members calls - other than under...,0,NaN,NaN,NaN,NaN,0,NaN,0
31,Other ancillary own funds,0,NaN,NaN,NaN,NaN,0,NaN,0
32,Total ancillary own funds,0,NaN,NaN,NaN,NaN,0,NaN,0
33,Available and eligible own funds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Total available own funds to meet the SCR,26 043 743,26 043 743,NaN,0,NaN,0,NaN,0
35,Total available own funds to meet the MCR,26 043 743,26 043 743,NaN,0,NaN,0,NaN,NaN
36,Total eligible own funds to meet the SCR,26 043 743,26 043 743,NaN,0,NaN,0,NaN,0
37,Total eligible own funds to meet the MCR,26 043 743,26 043 743,NaN,0,NaN,0,NaN,NaN

(1, 1)

,Total,Tier 1 - unrestricted,Tier 1 - restricted,Tier 2,Tier 3
*0,,,,,
Basic own funds before deduction for participations in other financial sector as foreseen in article 68 of Delegated,NaN,NaN,NaN,NaN,NaN
Regulation (EU) 2015/35,NaN,NaN,NaN,NaN,NaN
Ordinary share capital (gross of own shares),4 000 000,4 000 000,NaN,0,NaN
Share premium account related to ordinary share capital,0,0,NaN,0,NaN
"Initial funds, members' contributions or the equivalent basic own - fund item for mutual and mutual-type undertakings",0,0,NaN,0,NaN
Subordinated mutual member accounts,0,NaN,0,0,0
Surplus funds,0,0,NaN,NaN,NaN
Preference shares,0,NaN,0,0,0
Share premium account related to preference shares,0,NaN,0,0,0
Reconciliation reserve,22 043 743,22 043 743,NaN,NaN,NaN
Subordinated liabilities,0,NaN,0,0,0
An amount equal to the value of net deferred tax assets,0,NaN,NaN,NaN,0
Other own fund items approved by the supervisory authority as basic own funds not specified above,0,0,0,0,0
Own funds from the financial statements that should not be represented by the reconciliation reserve and do not meet the,NaN,NaN,NaN,NaN,NaN
criteria to be classified as Solvency II own funds,NaN,NaN,NaN,NaN,NaN
Own funds from the financial statements that should not be represented by the reconciliation reserve and do not meet the criteria,NaN,NaN,NaN,NaN,NaN
to be classified as Solvency II own funds,0,NaN,NaN,NaN,NaN
Deductions,NaN,NaN,NaN,NaN,NaN
Deductions for participations in financial and credit institutions,0,0,0,0,0
Total basic own funds after deductions,26 043 743,26 043 743,0,0,0
Ancillary own funds,NaN,NaN,NaN,NaN,NaN
Unpaid and uncalled ordinary share capital callable on demand,0,NaN,NaN,0,NaN
"Unpaid and uncalled initial funds, members' contributions or the equivalent basic own fund item for mutual and mutual - type",NaN,NaN,NaN,NaN,NaN
"undertakings, callable on demand",0,NaN,NaN,0,NaN
Unpaid and uncalled preference shares callable on demand,0,NaN,NaN,0,0
A legally binding commitment to subscribe and pay for subordinated liabilities on demand,0,NaN,NaN,0,0
Letters of credit and guarantees under Article 96(2) of the Directive 2009/138/EC,0,NaN,NaN,0,NaN
Letters of credit and guarantees other than under Article 96(2) of the Directive 2009/138/EC,0,NaN,NaN,0,0
Supplementary members calls under first subparagraph of Article 96(3) of the Directive 2009/138/EC,0,NaN,NaN,0,NaN
Supplementary members calls - other than under first subparagraph of Article 96(3) of the Directive 2009/138/EC,0,NaN,NaN,0,0
Other ancillary own funds,0,NaN,NaN,0,0
Total ancillary own funds,0,NaN,NaN,0,0
Available and eligible own funds,NaN,NaN,NaN,NaN,NaN
Total available own funds to meet the SCR,26 043 743,26 043 743,0,0,0
Total available own funds to meet the MCR,26 043 743,26 043 743,0,0,NaN
Total eligible own funds to meet the SCR,26 043 743,26 043 743,0,0,0
Total eligible own funds to meet the MCR,26 043 743,26 043 743,0,0,NaN

parsing 4 ../data/res\generali\tabula-Generali_2019_EN_short-12.csv

                                    0           1
0                                 SCR  12 883 886
1                                 MCR   3 220 972
2  Ratio of Eligible own funds to SCR      202,1%
3  Ratio of Eligible own funds to MCR      808,6%

(0, 1)

                                             1
0
SCR                                 12 883 886
MCR                                  3 220 972
Ratio of Eligible own funds to SCR      202,1%
Ratio of Eligible own funds to MCR      808,6%

parsing 5 ../data/res\generali\tabula-Generali_2019_EN_short-13.csv

                                                    0           1
0                              Reconciliation reserve         NaN
1                   Excess of assets over liabilities  29 260 743
2           Own shares (held directly and indirectly)           0
3    Foreseeable dividends, distributions and charges   3 217 000
4                          Other basic own fund items   4 000 000
5   Adjustment for restricted own fund items in re...           0
6                              Reconciliation reserve  22 043 743
7                                    Expected profits         NaN
8   Expected profits included in future premiums (...   9 065 463
9   Expected profits included in future premiums (...   1 799 884
10  Total Expected profits included in future prem...  10 865 348

(0, 1)

                                                             1
0
Reconciliation reserve                                     NaN
Excess of assets over liabilities                   29 260 743
Own shares (held directly and indirectly)                    0
Foreseeable dividends, distributions and charges     3 217 000
Other basic own fund items                           4 000 000
Adjustment for restricted own fund items in res...           0
Reconciliation reserve                              22 043 743
Expected profits                                           NaN
Expected profits included in future premiums (E...   9 065 463
Expected profits included in future premiums (E...   1 799 884
Total Expected profits included in future premi...  10 865 348

parsing 6 ../data/res\generali\tabula-Generali_2019_EN_short-14.csv

        0                           1          2          3
0   FIN01              Financial Risk  4 905 118  4 905 118
1   CRD01                 Credit Risk  2 433 843  2 433 843
2   LUW01      Life underwriting risk    646 860    646 860
3   HLT01    Health underwriting risk          0          0
4   NUW01  Non-life underwriting risk  2 291 470  2 291 470
5   OPE01            Operational risk    744 725          0
6   TAX01              Tax Cap Effect    624 514    624 514
7   MOD01            Model Adjustment    307 000    307 000
8   INT01             Intangible risk          0          0
9   SFA01     SF transferred Generali  2 902 608          0
10  SFA02    SF transferred CP Zdravi     65 799          0

(0, 2)

                                          2          3
0
FIN01 Financial Risk              4 905 118  4 905 118
CRD01 Credit Risk                 2 433 843  2 433 843
LUW01 Life underwriting risk        646 860    646 860
HLT01 Health underwriting risk            0          0
NUW01 Non-life underwriting risk  2 291 470  2 291 470
OPE01 Operational risk              744 725          0
TAX01 Tax Cap Effect                624 514    624 514
MOD01 Model Adjustment              307 000    307 000
INT01 Intangible risk                     0          0
SFA01 SF transferred Generali     2 902 608          0
SFA02 SF transferred CP Zdravi       65 799          0

parsing 7 ../data/res\generali\tabula-Generali_2019_EN_short-15.csv

                                                    0           1
0         Calculation of Solvency Capital Requirement         NaN
1                      Total undiversified components  14 921 938
2                                     Diversification  -2 038 052
3   Capital requirement for business operated in a...           0
4   Solvency capital requirement excluding capital...  12 883 886
5                         Capital add-ons already set           0
6                        Solvency capital requirement  12 883 886
7                            Other information on SCR         NaN
8   Amount/estimate of the overall loss-absorbing ...           0
9   Amount/estimate of the overall loss-absorbing ...           0
10  Capital requirement for duration-based equity ...         NaN
11  Total amount of Notional Solvency Capital Requ...           0
12  Total amount of Notional Solvency Capital Requ...         NaN
13  accordance with Art. 4 of Directive 2003/41/EC...           0
14  Total amount of Notional Solvency Capital Requ...           0
15  Diversification effects due to RFF nSCR aggreg...           0

(0, 1)

                                                             1
0
Calculation of Solvency Capital Requirement                NaN
Total undiversified components                      14 921 938
Diversification                                     -2 038 052
Capital requirement for business operated in ac...           0
Solvency capital requirement excluding capital ...  12 883 886
Capital add-ons already set                                  0
Solvency capital requirement                        12 883 886
Other information on SCR                                   NaN
Amount/estimate of the overall loss-absorbing c...           0
Amount/estimate of the overall loss-absorbing c...           0
Capital requirement for duration-based equity r...         NaN
Total amount of Notional Solvency Capital Requi...           0
Total amount of Notional Solvency Capital Requi...         NaN
accordance with Art. 4 of Directive 2003/41/EC ...           0
Total amount of Notional Solvency Capital Requi...           0
Diversification effects due to RFF nSCR aggrega...           0

parsing 8 ../data/res\generali\tabula-Generali_2019_EN_short-16.csv

,0,1,2
0,NaN,Non-life activities,Life activities
1,NaN,"MCR(NL,NL) Result","MCR(NL,L) Result"
2,Linear formula component for non-life insuranc...,NaN,NaN
3,obligations,1 774 072,160 194

(2, 1)

,"Non-life activities MCR(NL,NL) Result","Life activities MCR(NL,L) Result"
*0,,
Linear formula component for non-life insurance and reinsurance,NaN,NaN
obligations,1 774 072,160 194

parsing 9 ../data/res\generali\tabula-Generali_2019_EN_short-17.csv

,0,1,2,3,4
0,NaN,Net (of,NaN,Net (of,NaN
1,NaN,NaN,Net (of reinsurance),NaN,Net (of reinsurance)
2,NaN,reinsurance/SPV),NaN,reinsurance/SPV),NaN
3,NaN,NaN,written premiums in,NaN,written premiums in
4,NaN,best estimate and TP,NaN,best estimate and TP,NaN
5,NaN,NaN,the last 12 months,NaN,the last 12 months
6,NaN,calculated as a whole,NaN,calculated as a whole,NaN
7,Medical expense insurance and proportional rei...,57 092,113 617,NaN,NaN
8,Income protection insurance and proportional r...,5 040,276 793,1 222 855,NaN
9,Workers' compensation insurance and proportion...,0,0,NaN,NaN
10,Motor vehicle liability insurance and proporti...,3 541 155,3 192 117,NaN,NaN
11,Other motor insurance and proportional reinsur...,1 627 382,3 058 001,NaN,NaN
12,"Marine, aviation and transport insurance and p...",57 005,84 094,NaN,NaN
13,Fire and other damage to property insurance an...,1 755 991,3 871 375,NaN,NaN
14,General liability insurance and proportional r...,1 442 215,1 123 262,NaN,NaN
15,Credit and suretyship insurance and proportion...,92 776,16 296,NaN,NaN
16,Legal expenses insurance and proportional rein...,0,0,NaN,NaN
17,Assistance and proportional reinsurance,0,0,NaN,NaN
18,Miscellaneous financial loss insurance and pro...,7 850,15,NaN,NaN
19,Non-proportional health reinsurance,0,0,NaN,NaN
20,Non-proportional casualty reinsurance,4 364,0,NaN,NaN
21,"Non-proportional marine, aviation and transpor...",0,0,NaN,NaN
22,Non-proportional property reinsurance,519,67,NaN,NaN

(7, 1)

,Net (of reinsurance/SPV) best estimate and TP calculated as a whole,Net (of reinsurance) written premiums in the last 12 months,Net (of reinsurance/SPV) best estimate and TP calculated as a whole,Net (of reinsurance) written premiums in the last 12 months
*0,,,,
Medical expense insurance and proportional reinsurance,57 092,113 617,NaN,NaN
Income protection insurance and proportional reinsurance,5 040,276 793,1 222 855,NaN
Workers' compensation insurance and proportional reinsurance,0,0,NaN,NaN
Motor vehicle liability insurance and proportional reinsurance,3 541 155,3 192 117,NaN,NaN
Other motor insurance and proportional reinsurance,1 627 382,3 058 001,NaN,NaN
"Marine, aviation and transport insurance and proportional reinsurance",57 005,84 094,NaN,NaN
Fire and other damage to property insurance and proportional reinsurance,1 755 991,3 871 375,NaN,NaN
General liability insurance and proportional reinsurance,1 442 215,1 123 262,NaN,NaN
Credit and suretyship insurance and proportional reinsurance,92 776,16 296,NaN,NaN
Legal expenses insurance and proportional reinsurance,0,0,NaN,NaN
Assistance and proportional reinsurance,0,0,NaN,NaN
Miscellaneous financial loss insurance and proportional reinsurance,7 850,15,NaN,NaN
Non-proportional health reinsurance,0,0,NaN,NaN
Non-proportional casualty reinsurance,4 364,0,NaN,NaN
"Non-proportional marine, aviation and transport reinsurance",0,0,NaN,NaN
Non-proportional property reinsurance,519,67,NaN,NaN

parsing 10 ../data/res\generali\tabula-Generali_2019_EN_short-18.csv

,0,1,2
0,NaN,Non-life activities,Life activities
1,NaN,"MCR(L,NL) Result","MCR(L,L) Result"
2,Linear formula component for life insurance an...,NaN,NaN
3,obligations,19 011,1 147 709

(2, 1)

,"Non-life activities MCR(L,NL) Result","Life activities MCR(L,L) Result"
*0,,
Linear formula component for life insurance and reinsurance,NaN,NaN
obligations,19 011,1 147 709

parsing 11 ../data/res\generali\tabula-Generali_2019_EN_short-19.csv

,0,1,2,3,4
0,NaN,Non-life activities,NaN,NaN,Life activities
1,NaN,Net (of,NaN,Net (of,NaN
2,NaN,Net (of,NaN,NaN,Net (of
3,NaN,reinsurance/SPV),NaN,reinsurance/SPV),NaN
4,NaN,reinsurance/SPV),NaN,NaN,reinsurance/SPV)
5,NaN,best estimate and TP,NaN,best estimate and TP,NaN
6,NaN,total capital at risk,NaN,NaN,total capital at risk
7,NaN,calculated as a whole,NaN,calculated as a whole,NaN
8,Obligations with profit participation - guaran...,0,NaN,25 390 884,NaN
9,Obligations with profit participation - future...,0,NaN,345 717,NaN
10,Index-linked and unit-linked insurance obligat...,0,NaN,14 684 507,NaN
11,Other life (re)insurance and health (re)insura...,905 290,NaN,NaN,0
12,Total capital at risk for all life (re)insuran...,NaN,0,NaN,176 331 785

(8, 1)

,Non-life activities Net (of Net (of reinsurance/SPV) reinsurance/SPV) best estimate and TP total capital at risk calculated as a whole,*2,Net (of reinsurance/SPV) best estimate and TP calculated as a whole,Life activities Net (of reinsurance/SPV) total capital at risk
*0,,,,
Obligations with profit participation - guaranteed benefits,0,NaN,25 390 884,NaN
Obligations with profit participation - future discretionary benefits,0,NaN,345 717,NaN
Index-linked and unit-linked insurance obligations,0,NaN,14 684 507,NaN
Other life (re)insurance and health (re)insurance obligations,905 290,NaN,NaN,0
Total capital at risk for all life (re)insurance obligations,NaN,0,NaN,176 331 785

parsing 12 ../data/res\generali\tabula-Generali_2019_EN_short-2.csv

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN
1,NaN,NaN,NaN,Workers' compensation,NaN,Motor vehicle liability,NaN,"Marine, aviation and transport",Fire and other damage to,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Medical expense insurance,Income protection insurance,NaN,NaN,NaN,Other motor insurance,NaN,NaN,General liability insurance,...,Miscellaneous financial loss,Health,NaN,Casualty,NaN,"Marine, aviation, transport",Property,NaN,NaN,NaN
3,NaN,NaN,NaN,insurance,NaN,insurance,NaN,insurance,property insurance,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Premiums written,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Gross - Direct Business,190 524,460 974,NaN,0,5 264 304,5 190 172,346 051,6 915 826,2 172 093,...,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 565 998
6,Gross - Proportional reinsurance accepted,0,209,NaN,0,0,0,33 557,455 578,147 741,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,641 048
7,Gross - Non-proportional reinsurance accepted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3 327,NaN,39 915,408,NaN,101 345,NaN,144 995
8,Reinsurers' share,76 908,184 389,NaN,0,2 072 187,2 132 171,295 514,3 500 029,1 196 572,...,0,NaN,3 327,NaN,39 915,408,NaN,101 279,NaN,9 616 403
9,Net,113 617,276 793,NaN,0,3 192 117,3 058 001,84 094,3 871 375,1 123 262,...,15,NaN,0,NaN,-0,0,NaN,67,NaN,11 735 637
10,Premiums earned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Gross - Direct Business,191 275,463 828,NaN,0,5 233 601,5 112 392,349 712,6 917 796,2 140 322,...,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 543 828
12,Gross - Proportional reinsurance accepted,0,266,NaN,0,0,0,33 837,457 227,148 223,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,643 719
13,Gross - Non-proportional reinsurance accepted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3 327,NaN,39 915,408,NaN,101 345,NaN,144 995
14,Reinsurers' share,77 208,185 531,NaN,0,2 059 906,2 101 059,298 432,3 484 292,1 215 211,...,0,NaN,3 327,NaN,39 915,408,NaN,101 279,NaN,9 580 588
15,Net,114 067,278 562,NaN,0,3 173 695,3 011 333,85 117,3 890 730,1 073 334,...,15,NaN,0,NaN,-0,0,NaN,67,NaN,11 751 954
16,Claims incurred,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Gross - Direct Business,96 167,143 069,NaN,0,2 892 919,3 652 101,234 086,3 133 067,889 830,...,6 364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 042 849
18,Gross - Proportional reinsurance accepted,0,173,NaN,0,0,-4 266,8 073,189 626,129 058,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,324 322
19,Gross - Non-proportional reinsurance accepted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5 157,NaN,56 544,0,NaN,-31 651,NaN,30 049
20,Reinsurers' share,43 946,58 200,NaN,0,1 030 449,1 336 701,206 108,1 435 301,554 833,...,0,NaN,5 157,NaN,56 544,0,NaN,-31 651,NaN,4 698 085
21,Net,52 221,85 041,NaN,0,1 862 470,2 311 134,36 052,1 887 392,464 054,...,6 364,NaN,0,NaN,-0,0,NaN,-0,NaN,6 699 136
22,Changes in other technical provisions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Gross - Direct Business,0,0,NaN,0,0,0,0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
24,Gross - Proportional reinsurance accepted,0,0,NaN,0,0,0,0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
25,Gross - Non- proportional reinsurance accepted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,0,0,NaN,0,NaN,0
26,Reinsurers'share,0,0,NaN,0,0,0,0,0,0,...,0,NaN,0,NaN,0,0,NaN,0,NaN,0
27,Net,0,0,NaN,0,0,0,0,0,0,...,0,NaN,0,NaN,0,0,NaN,0,NaN,0
28,Expenses incurred,128 516,33 565,NaN,0,1 171 048,909 086,30 386,1 500 862,467 174,...,462,NaN,-16,NaN,-197,0,NaN,-467,NaN,4 320 146
29,Other expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159 873
30,Total expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4 480 020

(4, 1)

,Medical expense insurance,Income protection insurance,Workers' compensation insurance,Motor vehicle liability insurance,Other motor insurance,"Marine, aviation and transport insurance",Fire and other damage to property insurance,General liability insurance,Credit and suretyship insurance,Legal expenses insurance,Assistance,Miscellaneous financial loss,Health,Casualty,"Marine, aviation, transport",Property,Total
*0,,,,,,,,,,,,,,,,,
Premiums written,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gross - Direct Business,190 524,460 974,0,5 264 304,5 190 172,346 051,6 915 826,2 172 093,26 039,0,0,15,NaN,NaN,NaN,NaN,20 565 998
Gross - Proportional reinsurance accepted,0,209,0,0,0,33 557,455 578,147 741,3 963,0,0,0,NaN,NaN,NaN,NaN,641 048
Gross - Non-proportional reinsurance accepted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3 327,39 915,408,101 345,144 995
Reinsurers' share,76 908,184 389,0,2 072 187,2 132 171,295 514,3 500 029,1 196 572,13 705,0,0,0,3 327,39 915,408,101 279,9 616 403
Net,113 617,276 793,0,3 192 117,3 058 001,84 094,3 871 375,1 123 262,16 296,0,0,15,0,-0,0,67,11 735 637
Premiums earned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gross - Direct Business,191 275,463 828,0,5 233 601,5 112 392,349 712,6 917 796,2 140 322,134 888,0,0,15,NaN,NaN,NaN,NaN,20 543 828
Gross - Proportional reinsurance accepted,0,266,0,0,0,33 837,457 227,148 223,4 167,0,0,0,NaN,NaN,NaN,NaN,643 719
Gross - Non-proportional reinsurance accepted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3 327,39 915,408,101 345,144 995
Reinsurers' share,77 208,185 531,0,2 059 906,2 101 059,298 432,3 484 292,1 215 211,14 022,0,0,0,3 327,39 915,408,101 279,9 580 588
Net,114 067,278 562,0,3 173 695,3 011 333,85 117,3 890 730,1 073 334,125 033,0,0,15,0,-0,0,67,11 751 954
Claims incurred,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gross - Direct Business,96 167,143 069,0,2 892 919,3 652 101,234 086,3 133 067,889 830,-4 754,0,0,6 364,NaN,NaN,NaN,NaN,11 042 849
Gross - Proportional reinsurance accepted,0,173,0,0,-4 266,8 073,189 626,129 058,1 659,0,0,0,NaN,NaN,NaN,NaN,324 322
Gross - Non-proportional reinsurance accepted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5 157,56 544,0,-31 651,30 049
Reinsurers' share,43 946,58 200,0,1 030 449,1 336 701,206 108,1 435 301,554 833,2 496,0,0,0,5 157,56 544,0,-31 651,4 698 085
Net,52 221,85 041,0,1 862 470,2 311 134,36 052,1 887 392,464 054,-5 591,0,0,6 364,0,-0,0,-0,6 699 136
Changes in other technical provisions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gross - Direct Business,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,0
Gross - Proportional reinsurance accepted,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,0
Gross - Non- proportional reinsurance accepted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
Reinsurers'share,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Net,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Expenses incurred,128 516,33 565,0,1 171 048,909 086,30 386,1 500 862,467 174,79 728,0,0,462,-16,-197,0,-467,4 320 146
Other expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159 873
Total expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4 480 020

parsing 13 ../data/res\generali\tabula-Generali_2019_EN_short-20.csv

                             0           1
0                   Linear MCR   3 100 986
1                          SCR  12 883 886
2                      MCR cap   5 797 749
3                    MCR floor   3 220 972
4                 Combined MCR   3 220 972
5    Absolute floor of the MCR     188 756
6  Minimum Capital Requirement   3 220 972

(0, 1)

                                      1
0
Linear MCR                    3 100 986
SCR                          12 883 886
MCR cap                       5 797 749
MCR floor                     3 220 972
Combined MCR                  3 220 972
Absolute floor of the MCR       188 756
Minimum Capital Requirement   3 220 972

parsing 14 ../data/res\generali\tabula-Generali_2019_EN_short-21.csv

,0,1,2
0,Notional non-life and life MCR calculation,Non-life activities,Life activities
1,Notional linear MCR,1 793 083,1 307 903
2,Notional SCR excluding add-on (annual or lates...,7 449 849,5 434 038
3,Notional MCR cap,3 352 432,2 445 317
4,Notional MCR floor,1 862 462,1 358 509
5,Notional Combined MCR,1 862 462,1 358 509
6,Absolute floor of the notional MCR,94 378,94 378
7,Notional MCR,1 862 462,1 358 509

(1, 1)

,Non-life activities,Life activities
Notional non-life and life MCR calculation,,
Notional linear MCR,1 793 083,1 307 903
Notional SCR excluding add-on (annual or latest calculation),7 449 849,5 434 038
Notional MCR cap,3 352 432,2 445 317
Notional MCR floor,1 862 462,1 358 509
Notional Combined MCR,1 862 462,1 358 509
Absolute floor of the notional MCR,94 378,94 378
Notional MCR,1 862 462,1 358 509

parsing 15 ../data/res\generali\tabula-Generali_2019_EN_short-3.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Annuities stemming from non-,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,Annuities stemming from non-,NaN,NaN,NaN,NaN,Total,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,life insurance contracts and,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Insurance with profit,Index-linked and unit-linked,NaN,life insurance contracts and,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Health insurance,NaN,NaN,NaN,Other life insurance,NaN,relating to insurance,Health reinsurance,NaN,Life reinsurance,NaN,NaN
5,NaN,NaN,NaN,participation,insurance,NaN,relating to health insurance,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,obligations other than health,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,obligations,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,insurance obligations,NaN,NaN,NaN,NaN,NaN
9,Premiums written,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Gross,NaN,0,2 814 069,1 604 467,3 317 561,0,0,NaN,0,10 750,NaN,7 746 847
11,Reinsurers' share,NaN,0,0,0,1 265 427,0,0,NaN,0,10 774,NaN,1 276 202
12,Net,NaN,0,2 814 069,1 604 467,2 052 134,0,0,NaN,0,-24,NaN,6 470 646
13,Premiums earned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Gross,NaN,0,2 814 069,1 604 467,3 317 561,0,0,NaN,0,10 750,NaN,7 746 847
15,Reinsurers' share,NaN,0,0,0,1 265 427,0,0,NaN,0,10 774,NaN,1 276 202
16,Net,NaN,0,2 814 069,1 604 467,2 052 134,0,0,NaN,0,-24,NaN,6 470 646
17,Claims incurred,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Gross,NaN,0,4 390 077,1 110 123,1 114 718,0,-91 814,NaN,0,11 778,NaN,6 534 883
19,Reinsurers' share,NaN,0,0,0,388 785,0,-22 783,NaN,0,11 778,NaN,377 780
20,Net,NaN,0,4 390 077,1 110 123,725 933,0,-69 030,NaN,0,-0,NaN,6 157 103
21,Changes in other technical provisions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Gross,NaN,0,2 511 174,-1 528 257,-14 208,0,0,NaN,0,24,NaN,968 733
23,Reinsurers' share,NaN,0,0,0,-16 829,0,0,NaN,0,-0,NaN,-16 829
24,Net,NaN,0,2 511 174,-1 528 257,2 621,0,0,NaN,0,24,NaN,985 562
25,Expenses incurred,NaN,0,628 023,74 434,471 227,0,0,NaN,0,-585,NaN,1 173 098
26,Other expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92 631
27,Total expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 265 729

(9, 1)

,Health insurance,*2,Insurance with profit participation,Index-linked and unit-linked insurance,Other life insurance,Annuities stemming from non- life insurance contracts and relating to health insurance obligations,Annuities stemming from non- life insurance contracts and relating to insurance obligations other than health insurance obligations,Health reinsurance,Life reinsurance,Total
*0,,,,,,,,,,
Premiums written,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gross,NaN,0,2 814 069,1 604 467,3 317 561,0,0,0,10 750,7 746 847
Reinsurers' share,NaN,0,0,0,1 265 427,0,0,0,10 774,1 276 202
Net,NaN,0,2 814 069,1 604 467,2 052 134,0,0,0,-24,6 470 646
Premiums earned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gross,NaN,0,2 814 069,1 604 467,3 317 561,0,0,0,10 750,7 746 847
Reinsurers' share,NaN,0,0,0,1 265 427,0,0,0,10 774,1 276 202
Net,NaN,0,2 814 069,1 604 467,2 052 134,0,0,0,-24,6 470 646
Claims incurred,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gross,NaN,0,4 390 077,1 110 123,1 114 718,0,-91 814,0,11 778,6 534 883
Reinsurers' share,NaN,0,0,0,388 785,0,-22 783,0,11 778,377 780
Net,NaN,0,4 390 077,1 110 123,725 933,0,-69 030,0,-0,6 157 103
Changes in other technical provisions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gross,NaN,0,2 511 174,-1 528 257,-14 208,0,0,0,24,968 733
Reinsurers' share,NaN,0,0,0,-16 829,0,0,0,-0,-16 829
Net,NaN,0,2 511 174,-1 528 257,2 621,0,0,0,24,985 562
Expenses incurred,NaN,0,628 023,74 434,471 227,0,0,0,-585,1 173 098
Other expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92 631
Total expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 265 729

parsing 16 ../data/res\generali\tabula-Generali_2019_EN_short-4.csv

,0,1,2,3,4,5,6,7,8
0,NaN,Home Country,NaN,NaN,Top 5 countries (by amount of gross premiums w...,NaN,NaN,NaN,Total Top 5 and home country
1,NaN,NaN,BG,NaN,PL HU RS,NaN,RU,NaN,NaN
2,Premiums written,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Gross - Direct Business,20 565 998,NaN,0,0 0,0,NaN,0,20 565 998
4,Gross - Proportional reinsurance accepted,497 802,NaN,128 383,12 933 8 537,476,NaN,0,648 131
5,Gross - Non-proportional reinsurance accepted,67,NaN,144 828,0 0,0,NaN,101,144 995
6,Reinsurers' share,9 335 609,NaN,273 211,0 7 483,0,NaN,101,9 616 403
7,Net,11 728 258,NaN,0,12 933 1 054,476,NaN,0,11 742 721
8,Premiums earned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Gross - Direct Business,20 543 828,NaN,0,0 0,0,NaN,0,20 543 828
10,Gross - Proportional reinsurance accepted,500 186,NaN,128 618,11 957 8 537,476,NaN,0,649 774
11,Gross - Non-proportional reinsurance accepted,67,NaN,144 828,0 0,0,NaN,101,144 995
12,Reinsurers' share,9 299 416,NaN,273 446,0 7 483,0,NaN,101,9 580 446
13,Net,11 744 664,NaN,0,11 957 1 054,476,NaN,0,11 758 152
14,Claims incurred,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Gross - Direct Business,11 042 849,NaN,0,0 0,0,NaN,0,11 042 849
16,Gross - Proportional reinsurance accepted,308 848,NaN,63 086,-19 363 2 928,0,NaN,-108,355 391
17,Gross - Non-proportional reinsurance accepted,0,NaN,30 782,0 0,0,NaN,-732,30 050
18,Reinsurers' share,4 633 191,NaN,93 868,0 2 928,0,NaN,-840,4 729 147
19,Net,6 718 506,NaN,0,-19 363 -0,0,NaN,-0,6 699 143
20,Changes in other technical provisions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Gross - Direct Business,0,NaN,0,0 0,0,NaN,0,0
22,Gross - Proportional reinsurance accepted,0,NaN,0,0 0,0,NaN,0,0
23,Gross - Non- proportional reinsurance accepted,0,NaN,0,0 0,0,NaN,0,0
24,Reinsurers'share,0,NaN,0,0 0,0,NaN,0,0
25,Net,0,NaN,0,0 0,0,NaN,0,0
26,Expenses incurred,4 318 964,NaN,-1 357,3 880 480,24,NaN,-3,4 321 988
27,Other expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159 873
28,Total expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4 481 861

(2, 1)

,Home Country,BG,Top 5 countries (by amount of gross premiums written) - non-life obligations PL HU RS,*5,RU,Total Top 5 and home country
*0,,,,,,
Premiums written,NaN,NaN,NaN,NaN,NaN,NaN
Gross - Direct Business,20 565 998,0,0 0,0,0,20 565 998
Gross - Proportional reinsurance accepted,497 802,128 383,12 933 8 537,476,0,648 131
Gross - Non-proportional reinsurance accepted,67,144 828,0 0,0,101,144 995
Reinsurers' share,9 335 609,273 211,0 7 483,0,101,9 616 403
Net,11 728 258,0,12 933 1 054,476,0,11 742 721
Premiums earned,NaN,NaN,NaN,NaN,NaN,NaN
Gross - Direct Business,20 543 828,0,0 0,0,0,20 543 828
Gross - Proportional reinsurance accepted,500 186,128 618,11 957 8 537,476,0,649 774
Gross - Non-proportional reinsurance accepted,67,144 828,0 0,0,101,144 995
Reinsurers' share,9 299 416,273 446,0 7 483,0,101,9 580 446
Net,11 744 664,0,11 957 1 054,476,0,11 758 152
Claims incurred,NaN,NaN,NaN,NaN,NaN,NaN
Gross - Direct Business,11 042 849,0,0 0,0,0,11 042 849
Gross - Proportional reinsurance accepted,308 848,63 086,-19 363 2 928,0,-108,355 391
Gross - Non-proportional reinsurance accepted,0,30 782,0 0,0,-732,30 050
Reinsurers' share,4 633 191,93 868,0 2 928,0,-840,4 729 147
Net,6 718 506,0,-19 363 -0,0,-0,6 699 143
Changes in other technical provisions,NaN,NaN,NaN,NaN,NaN,NaN
Gross - Direct Business,0,0,0 0,0,0,0
Gross - Proportional reinsurance accepted,0,0,0 0,0,0,0
Gross - Non- proportional reinsurance accepted,0,0,0 0,0,0,0
Reinsurers'share,0,0,0 0,0,0,0
Net,0,0,0 0,0,0,0
Expenses incurred,4 318 964,-1 357,3 880 480,24,-3,4 321 988
Other expenses,NaN,NaN,NaN,NaN,NaN,159 873
Total expenses,NaN,NaN,NaN,NaN,NaN,4 481 861

parsing 17 ../data/res\generali\tabula-Generali_2019_EN_short-5.csv

,0,1,2,3,4,5,6
0,NaN,Home Country,NaN,Top 5 countries (by amount of gross premiums w...,NaN,NaN,Total Top 5 and home country
1,Premiums written,NaN,NaN,NaN,NaN,NaN,NaN
2,Gross,7 746 847,0,0 0,0,0,7 746 847
3,Reinsurers' share,1 276 202,0,0 0,0,0,1 276 202
4,Net,6 470 646,0,0 0,0,0,6 470 646
5,Premiums earned,NaN,NaN,NaN,NaN,NaN,0
6,Gross,7 746 847,0,0 0,0,0,7 746 847
7,Reinsurers' share,1 276 202,0,0 0,0,0,1 276 202
8,Net,6 470 646,0,0 0,0,0,6 470 646
9,Claims incurred,NaN,NaN,NaN,NaN,NaN,0
10,Gross,6 534 883,0,0 0,0,0,6 534 883
11,Reinsurers' share,377 780,0,0 0,0,0,377 780
12,Net,6 157 103,0,0 0,0,0,6 157 103
13,Changes in other technical provisions,NaN,NaN,NaN,NaN,NaN,0
14,Gross,968 733,0,0 0,0,0,968 733
15,Reinsurers' share,-16 829,0,0 0,0,0,-16 829
16,Net,985 562,0,0 0,0,0,985 562
17,Expenses incurred,1 173 098,0,0 0,0,0,1 173 098
18,Other expenses,NaN,NaN,NaN,NaN,NaN,92 631
19,Total expenses,NaN,NaN,NaN,NaN,NaN,1 265 729

(1, 1)

,Home Country,*2,Top 5 countries (by amount of gross premiums written) - life obligations,*4,*5,Total Top 5 and home country
*0,,,,,,
Premiums written,NaN,NaN,NaN,NaN,NaN,NaN
Gross,7 746 847,0,0 0,0,0,7 746 847
Reinsurers' share,1 276 202,0,0 0,0,0,1 276 202
Net,6 470 646,0,0 0,0,0,6 470 646
Premiums earned,NaN,NaN,NaN,NaN,NaN,0
Gross,7 746 847,0,0 0,0,0,7 746 847
Reinsurers' share,1 276 202,0,0 0,0,0,1 276 202
Net,6 470 646,0,0 0,0,0,6 470 646
Claims incurred,NaN,NaN,NaN,NaN,NaN,0
Gross,6 534 883,0,0 0,0,0,6 534 883
Reinsurers' share,377 780,0,0 0,0,0,377 780
Net,6 157 103,0,0 0,0,0,6 157 103
Changes in other technical provisions,NaN,NaN,NaN,NaN,NaN,0
Gross,968 733,0,0 0,0,0,968 733
Reinsurers' share,-16 829,0,0 0,0,0,-16 829
Net,985 562,0,0 0,0,0,985 562
Expenses incurred,1 173 098,0,0 0,0,0,1 173 098
Other expenses,NaN,NaN,NaN,NaN,NaN,92 631
Total expenses,NaN,NaN,NaN,NaN,NaN,1 265 729

parsing 18 ../data/res\generali\tabula-Generali_2019_EN_short-6.csv

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,NaN,Index-linked and unit-linked insurance Other l...,NaN,NaN,NaN,NaN,Health insurance (direct business),NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,Annuities stemming,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Annuities stemming,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,from non-life insurance,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,Total (Life other than,NaN,from non-life insurance,NaN,NaN,NaN
5,NaN,Insurance with profit,NaN,NaN,contracts and relating,NaN,NaN,NaN,NaN,NaN,Health reinsurance,Total (Health similar
6,NaN,NaN,NaN,NaN,NaN,Accepted reinsurance,"health insurance,",NaN,contracts and relating,NaN,NaN,NaN
7,NaN,participation,Contracts without Contracts with options Contr...,Contracts with options,to insurance obligation,NaN,NaN,Contracts without Contracts with options,NaN,NaN,(reinsurance accepted),to life insurance)
8,NaN,NaN,to health insurance options and guarantees or ...,or guarantees,other than health,NaN,incl. Unit-Linked),options and guarantees or guarantees,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,obligations,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,insurance obligations,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Technical provisions calculated as a whole,0,0 0,NaN,0,0,0,0,NaN,0,0,0
12,Total Recoverables from reinsurance/SPV and Fi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,for expected losses due to counterparty defaul...,0,0 0,NaN,0,0,0,0,NaN,0,0,0
14,Technical provisions calculated as a sum of BE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Best Estimate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Gross Best Estimate,25 733 342,14 671 043 0 -2 179 512,0,1 421 497,0,39 646 371,0 0,NaN,0,0,0
17,Total Recoverables from reinsurance/SPV and Fi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,for expected losses due to counterparty default,-3 259,-13 464 0 82 561,0,516 207,0,582 045,0 0,NaN,0,0,0
19,Best estimate minus recoverables from reinsura...,25 736 601,14 684 507 0 -2 262 073,0,905 290,0,39 064 326,0 0,NaN,0,0,0
20,Risk Margin,427 686,366 302 532 573,NaN,79 581,0,1 406 142,0,NaN,0,0,0
21,Amount of the transitional on Technical Provis...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Technical Provisions calculated as a whole,0,0 0,NaN,0,0,0,0,NaN,0,0,0
23,Best estimate,0,0 0 0,0,0,0,0,0 0,NaN,0,0,0
24,Risk margin,0,0 0,NaN,0,0,0,0,NaN,0,0,0
25,Technical provisions - total,26 161 029,15 037 345 -1 646 939,NaN,1 501 078,0,41 052 512,0,NaN,0,0,0

(11, 1)

,Insurance with profit participation,Index-linked and unit-linked insurance Other life insurance Contracts without Contracts with options Contracts without to health insurance options and guarantees or guarantees options and guarantees,Contracts with options or guarantees,Annuities stemming from non-life insurance contracts and relating to insurance obligation other than health insurance obligations,Accepted reinsurance,"Total (Life other than health insurance, incl. Unit-Linked)",Health insurance (direct business) Contracts without Contracts with options options and guarantees or guarantees,Annuities stemming from non-life insurance contracts and relating obligations,Health reinsurance (reinsurance accepted),Total (Health similar to life insurance)
*0,,,,,,,,,,
Technical provisions calculated as a whole,0,0 0,NaN,0,0,0,0,0,0,0
Total Recoverables from reinsurance/SPV and Finite Re after the adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
for expected losses due to counterparty default associated to TP as a whole,0,0 0,NaN,0,0,0,0,0,0,0
Technical provisions calculated as a sum of BE and RM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Best Estimate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gross Best Estimate,25 733 342,14 671 043 0 -2 179 512,0,1 421 497,0,39 646 371,0 0,0,0,0
Total Recoverables from reinsurance/SPV and Finite Re after the adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
for expected losses due to counterparty default,-3 259,-13 464 0 82 561,0,516 207,0,582 045,0 0,0,0,0
Best estimate minus recoverables from reinsurance/SPV and Finite Re,25 736 601,14 684 507 0 -2 262 073,0,905 290,0,39 064 326,0 0,0,0,0
Risk Margin,427 686,366 302 532 573,NaN,79 581,0,1 406 142,0,0,0,0
Amount of the transitional on Technical Provisions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Technical Provisions calculated as a whole,0,0 0,NaN,0,0,0,0,0,0,0
Best estimate,0,0 0 0,0,0,0,0,0 0,0,0,0
Risk margin,0,0 0,NaN,0,0,0,0,0,0,0
Technical provisions - total,26 161 029,15 037 345 -1 646 939,NaN,1 501 078,0,41 052 512,0,0,0,0

parsing 19 ../data/res\generali\tabula-Generali_2019_EN_short-7.csv

,0,1,2,3,4,5,6
0,NaN,NaN,NaN,NaN,NaN,Total Non-Life Workers' Non-proportional,NaN
1,NaN,Medical expense,NaN,Income protection,NaN,obligationscompensation Motor vehicle liabilit...,Non-proportional
2,NaN,insurance,NaN,insurance,NaN,insurance transport insurance to property insu...,property reinsurance
3,NaN,NaN,NaN,NaN,NaN,insurance transport reinsurance,NaN
4,Technical provisions calculated as a whole,0,NaN,0,NaN,0 0 0 0 0 0 0 0 0 0 0 0,0 0 0
5,Total Recoverables from reinsurance/SPV and Fi...,NaN,NaN,NaN,NaN,NaN,NaN
6,for expected losses due to counterparty defaul...,0,NaN,0,NaN,0 0 0 0 0 0 0 0 0 0 0 0,0 0 0
7,Technical provisions calculated as a sum of BE...,NaN,NaN,NaN,NaN,NaN,NaN
8,Best estimate,NaN,NaN,NaN,NaN,NaN,NaN
9,Premium provisions,NaN,NaN,NaN,NaN,NaN,NaN
10,Gross,8 489,NaN,13 858,NaN,0 829 486 929 091 2 266 344 156 262 013 58 113...,0 0 2 447 473
11,Total recoverable from reinsurance/SPV and Fin...,NaN,NaN,NaN,NaN,NaN,NaN
12,expected losses due to counterparty default,2 244,NaN,5 629,NaN,0 203 724 208 116 3 035 -185 791 -25 678 -7 69...,0 0 203 589
13,Net Best Estimate of Premium Provisions,6 245,NaN,8 229,NaN,0 625 763 720 975 -769 529 946 287 691 65 803 ...,0 0 2 243 884
14,Claims provisions,NaN,NaN,NaN,NaN,NaN,NaN
15,Gross,81 756,NaN,1 800 005,NaN,0 4 461 680 1 298 456 339 646 2 991 043 2 611 ...,0 116 742 13 905 880
16,Total recoverable from reinsurance/SPV and Fin...,NaN,NaN,NaN,NaN,NaN,NaN
17,expected losses due to counterparty default,30 909,NaN,580 340,NaN,0 1 546 287 392 048 281 872 1 764 998 1 457 07...,0 116 223 6 335 520
18,Net Best Estimate of Claims Provisions,50 847,NaN,1 219 665,NaN,0 2 915 392 906 407 57 774 1 226 045 1 154 524...,0 519 7 570 360
19,Total Best estimate - gross,90 245,NaN,1 813 863,NaN,0 5 291 166 2 227 547 341 912 3 335 199 2 873 ...,0 116 742 16 353 353
20,Total Best estimate - net,57 092,NaN,1 227 894,NaN,0 3 541 155 1 627 382 57 005 1 755 991 1 442 2...,0 519 9 814 243
21,Risk margin,928,NaN,25 257,NaN,0 336 205 46 946 6 308 142 839 147 281 5 949 0...,0 871 734 170
22,Amount of the transitional on Technical Provis...,NaN,NaN,NaN,NaN,NaN,NaN
23,Technical Provisions calculated as a whole,0,NaN,0,NaN,0 0 0 0 0 0 0 0 0 0 0 0,0 0 0
24,Best estimate,0,NaN,0,NaN,0 0 0 0 0 0 0 0 0 0 0 0,0 0 0
25,Risk margin,0,NaN,0,NaN,0 0 0 0 0 0 0 0 0 0 0 0,0 0 0
26,Technical provisions - total,NaN,NaN,NaN,NaN,NaN,NaN
27,Technical provisions - total,91 173,NaN,1 839 120,NaN,0 5 627 371 2 274 493 348 220 3 478 037 3 020 ...,0 117 614 17 087 523
28,Recoverable from reinsurance contract/SPV and ...,NaN,NaN,NaN,NaN,NaN,NaN
29,for expected losses due to counterparty defaul...,33 152,NaN,585 968,NaN,0 1 750 011 600 165 284 907 1 579 208 1 431 39...,0 116 223 6 539 109
30,Technical provisions minus recoverables from r...,NaN,NaN,NaN,NaN,NaN,NaN
31,total,58 020,NaN,1 253 152,NaN,0 3 877 361 1 674 328 63 314 1 898 830 1 589 4...,0 1 390 10 548 413

(4, 1)

,Medical expense insurance,*2,Income protection insurance,*4,"Total Non-Life Workers' Non-proportional obligationscompensation Motor vehicle liability Other motor insurance Marine, aviation and Fire and other damage General liability Credit and suretyship Legal expenses Assistance Miscellaneous financial Non-proportional Non-proportional marine, aviation and insurance transport insurance to property insurance insurance insurance insurance loss health reinsurance casualty reinsurance insurance transport reinsurance",Non-proportional property reinsurance
*0,,,,,,
Technical provisions calculated as a whole,0,NaN,0,NaN,0 0 0 0 0 0 0 0 0 0 0 0,0 0 0
Total Recoverables from reinsurance/SPV and Finite Re after the adjustment,NaN,NaN,NaN,NaN,NaN,NaN
for expected losses due to counterparty default associated to TP as a whole,0,NaN,0,NaN,0 0 0 0 0 0 0 0 0 0 0 0,0 0 0
Technical provisions calculated as a sum of BE and RM,NaN,NaN,NaN,NaN,NaN,NaN
Best estimate,NaN,NaN,NaN,NaN,NaN,NaN
Premium provisions,NaN,NaN,NaN,NaN,NaN,NaN
Gross,8 489,NaN,13 858,NaN,0 829 486 929 091 2 266 344 156 262 013 58 113...,0 0 2 447 473
Total recoverable from reinsurance/SPV and Finite Re after the adjustment for,NaN,NaN,NaN,NaN,NaN,NaN
expected losses due to counterparty default,2 244,NaN,5 629,NaN,0 203 724 208 116 3 035 -185 791 -25 678 -7 69...,0 0 203 589
Net Best Estimate of Premium Provisions,6 245,NaN,8 229,NaN,0 625 763 720 975 -769 529 946 287 691 65 803 ...,0 0 2 243 884
Claims provisions,NaN,NaN,NaN,NaN,NaN,NaN
Gross,81 756,NaN,1 800 005,NaN,0 4 461 680 1 298 456 339 646 2 991 043 2 611 ...,0 116 742 13 905 880
Total recoverable from reinsurance/SPV and Finite Re after the adjustment for,NaN,NaN,NaN,NaN,NaN,NaN
expected losses due to counterparty default,30 909,NaN,580 340,NaN,0 1 546 287 392 048 281 872 1 764 998 1 457 07...,0 116 223 6 335 520
Net Best Estimate of Claims Provisions,50 847,NaN,1 219 665,NaN,0 2 915 392 906 407 57 774 1 226 045 1 154 524...,0 519 7 570 360
Total Best estimate - gross,90 245,NaN,1 813 863,NaN,0 5 291 166 2 227 547 341 912 3 335 199 2 873 ...,0 116 742 16 353 353
Total Best estimate - net,57 092,NaN,1 227 894,NaN,0 3 541 155 1 627 382 57 005 1 755 991 1 442 2...,0 519 9 814 243
Risk margin,928,NaN,25 257,NaN,0 336 205 46 946 6 308 142 839 147 281 5 949 0...,0 871 734 170
Amount of the transitional on Technical Provisions,NaN,NaN,NaN,NaN,NaN,NaN
Technical Provisions calculated as a whole,0,NaN,0,NaN,0 0 0 0 0 0 0 0 0 0 0 0,0 0 0
Best estimate,0,NaN,0,NaN,0 0 0 0 0 0 0 0 0 0 0 0,0 0 0
Risk margin,0,NaN,0,NaN,0 0 0 0 0 0 0 0 0 0 0 0,0 0 0
Technical provisions - total,NaN,NaN,NaN,NaN,NaN,NaN
Technical provisions - total,91 173,NaN,1 839 120,NaN,0 5 627 371 2 274 493 348 220 3 478 037 3 020 ...,0 117 614 17 087 523
Recoverable from reinsurance contract/SPV and Finite Re after the adjustment,NaN,NaN,NaN,NaN,NaN,NaN
for expected losses due to counterparty default - total,33 152,NaN,585 968,NaN,0 1 750 011 600 165 284 907 1 579 208 1 431 39...,0 116 223 6 539 109
Technical provisions minus recoverables from reinsurance/SPV and Finite Re -,NaN,NaN,NaN,NaN,NaN,NaN
total,58 020,NaN,1 253 152,NaN,0 3 877 361 1 674 328 63 314 1 898 830 1 589 4...,0 1 390 10 548 413

parsing 20 ../data/res\generali\tabula-Generali_2019_EN_short-8.csv

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,In Current year
1,NaN,NaN,(cumulative)0 1,2,3,4,5,6,7,8,9,10 & +,NaN
2,Prior,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41 475,41 475
3,N-9,NaN,10 458 285 4 435 794,704 758,372 030,155 089,NaN,32 743,55 786,28 002,14 857,8 427,8 427 16 265 769
4,N-8,NaN,7 970 713 2 892 937,644 636,245 106,143 573,NaN,94 910,-1 007,35 790,27 907,NaN,27 907 12 054 565
5,N-7,NaN,8 069 615 3 162 243,662 292,278 304,116 991,NaN,46 108,27 367,15 842,NaN,NaN,15 842 12 378 762
6,N-6,NaN,9 053 606 3 412 051,856 059,314 420,NaN,98 375,47 755,30 188,NaN,NaN,NaN,30 188 13 812 454
7,N-5,NaN,7 262 646 3 271 802,894 217,321 285,112 456,NaN,42 700,NaN,NaN,NaN,NaN,42 700 11 905 107
8,N-4,NaN,6 948 787 3 147 119,754 090,414 475,219 201,NaN,NaN,NaN,NaN,NaN,NaN,219 201 11 483 672
9,N-3,NaN,7 688 475 3 291 810,738 240,408 500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,408 500 12 127 026
10,N-2,NaN,7 929 920 3 590 110,949 011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,949 011 12 469 041
11,N-1,NaN,8 228 043 3 661 099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3 661 099 11 889 142
12,NaN,N,9 241 687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9 241 687 9 241 687
13,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14 646 038 123 627 225

(2, 2)

,(cumulative)0 1,2,3,4,5,6,7,8,9,10 & +,In Current year
*0,,,,,,,,,,,
Prior,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41 475,41 475
N-9,10 458 285 4 435 794,704 758,372 030,155 089,NaN,32 743,55 786,28 002,14 857,8 427,8 427 16 265 769
N-8,7 970 713 2 892 937,644 636,245 106,143 573,NaN,94 910,-1 007,35 790,27 907,NaN,27 907 12 054 565
N-7,8 069 615 3 162 243,662 292,278 304,116 991,NaN,46 108,27 367,15 842,NaN,NaN,15 842 12 378 762
N-6,9 053 606 3 412 051,856 059,314 420,NaN,98 375,47 755,30 188,NaN,NaN,NaN,30 188 13 812 454
N-5,7 262 646 3 271 802,894 217,321 285,112 456,NaN,42 700,NaN,NaN,NaN,NaN,42 700 11 905 107
N-4,6 948 787 3 147 119,754 090,414 475,219 201,NaN,NaN,NaN,NaN,NaN,NaN,219 201 11 483 672
N-3,7 688 475 3 291 810,738 240,408 500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,408 500 12 127 026
N-2,7 929 920 3 590 110,949 011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,949 011 12 469 041
N-1,8 228 043 3 661 099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3 661 099 11 889 142
N,9 241 687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9 241 687 9 241 687
Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14 646 038 123 627 225

parsing 21 ../data/res\generali\tabula-Generali_2019_EN_short-9.csv

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Development year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Year end
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(discounted
2,NaN,NaN,0,NaN,1,NaN,2,NaN,3,NaN,...,5,6,NaN,7,NaN,8,NaN,9,10 & +,data)
3,Prior,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,420 364,377 027
4,N-9,NaN,0,NaN,0,NaN,0,NaN,0,NaN,...,0,0,NaN,0,NaN,0,NaN,162 994,NaN,146 406
5,N-8,NaN,0,NaN,0,NaN,0,NaN,0,NaN,...,0,0,NaN,0,NaN,164 871,NaN,NaN,NaN,147 961
6,N-7,NaN,0,NaN,0,NaN,0,NaN,0,NaN,...,0,0,NaN,144 318,NaN,NaN,NaN,NaN,NaN,129 259
7,N-6,NaN,0,NaN,0,NaN,0,NaN,0,NaN,...,0,198 013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178 342
8,N-5,NaN,0,NaN,0,NaN,0,NaN,0,NaN,...,322 650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288 757
9,N-4,NaN,0,NaN,0,NaN,0,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,413 781
10,N-3,NaN,0,NaN,0,NaN,0,NaN,702 378,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,641 280
11,N-2,NaN,0,NaN,0,NaN,1 487 727,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 386 980
12,N-1,NaN,0,NaN,2 088 937,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 927 008
13,NaN,N,5 867 492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5 472 955
14,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 109 755

(3, -1)

,*1,0,*3,1,*5,2,*7,3,*9,4,...,Development year 5,6,*14,7,*16,8,*18,9,10 & +,Year end (discounted data)
*0,,,,,,,,,,,,,,,,,,,,,
Prior,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,420 364,377 027
N-9,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,...,0,0,NaN,0,NaN,0,NaN,162 994,NaN,146 406
N-8,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,...,0,0,NaN,0,NaN,164 871,NaN,NaN,NaN,147 961
N-7,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,...,0,0,NaN,144 318,NaN,NaN,NaN,NaN,NaN,129 259
N-6,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,...,0,198 013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178 342
N-5,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,...,322 650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288 757
N-4,NaN,0,NaN,0,NaN,0,NaN,0,NaN,457 880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,413 781
N-3,NaN,0,NaN,0,NaN,0,NaN,702 378,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,641 280
N-2,NaN,0,NaN,0,NaN,1 487 727,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 386 980
N-1,NaN,0,NaN,2 088 937,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 927 008
NaN,N,5 867 492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5 472 955
Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 109 755

total_numbers 2230